### ISSUE TITLE
Error handling?

### ISSUE THREAD

**Issue by ashrude** [knopkem/dicom-dimse-native#61]
Hi! Is there any way to get any errors that occur?
Currently when I run findScu with a server that doesn't exist, the response is this:

```
{
  code: 0,
  container: null,
  message: 'request succeeded',
  status: 'success'
}
```

In stdout it logs this:

```
E: Association Rejected:
E: Result: Rejected Permanent, Source: Service User
E: Reason: Called AE Title Not Recognized
```

However, the response I get in the callback is the same as if there were just no studies, not that there was an error with the request.

Thanks!

**Comment by knopkem** [comment]
Hi,
in general the errors (coming from dcmtk) should be caught and returned in the above structure. However, checking the code it seems that I missed a condition check in the find-scu handler. The other SCUs (e.g. echo-scu) should behave correctly though.
So, this is easy to fix, but need to find some time to build a new release.

**Comment by knopkem** [comment]
This is fixed in the latest release now

**Comment by geezer78** [comment]
i believe the same issue ( errors not being caught)  is still present in the moveSCU'.

i get the same json status:
```
{
  code: 0,
  container: null,
  message: 'request succeeded',
  status: 'success'
}
```

while my dicom.log shows what actually happens:

`DEBUG [17-04-2025 13:21:53:984]: ======================= END A-ASSOCIATE-AC ======================
INFO  [17-04-2025 13:21:53:989]: Association Aborted
DEBUG [17-04-2025 13:21:53:990]: DcmDataset::read() TransferSyntax="Little Endian Implicit"
INFO  [17-04-2025 13:21:53:991]: Received C-MOVE Response
DEBUG [17-04-2025 13:21:53:991]: ===================== INCOMING DIMSE MESSAGE ====================
DEBUG [17-04-2025 13:21:53:991]: Message Type                  : C-MOVE RSP
DEBUG [17-04-2025 13:21:53:991]: Presentation Context ID       : 1
DEBUG [17-04-2025 13:21:53:991]: Message ID Being Responded To : 1
DEBUG [17-04-2025 13:21:53:991]: Affected SOP Class UID        : MOVEStudyRootQueryRetrieveInformationModel
DEBUG [17-04-2025 13:21:53:991]: Remaining Suboperations       : none
DEBUG [17-04-2025 13:21:53:991]: Completed Suboperations       : none
DEBUG [17-04-2025 13:21:53:991]: Failed Suboperations          : none
DEBUG [17-04-2025 13:21:53:991]: Warning Suboperations         : none
DEBUG [17-04-2025 13:21:53:991]: Data Set                      : none
DEBUG [17-04-2025 13:21:53:991]: DIMSE Status                  : 0xc000: Failed: Unable to process
DEBUG [17-04-2025 13:21:53:991]: ======================= END DIMSE MESSAGE =======================
DEBUG [17-04-2025 13:21:53:991]: Response has status detail:
DEBUG [17-04-2025 13:21:53:991]: 
DEBUG [17-04-2025 13:21:53:991]: # Dicom-Data-Set
DEBUG [17-04-2025 13:21:53:991]: # Used TransferSyntax: Little Endian Implicit
DEBUG [17-04-2025 13:21:53:991]: (0000,0902) LO [Abstract Syntax not supported by Storage Service Class Provider] #  64, 1 ErrorComment
DEBUG [17-04-2025 13:21:53:991]: 
DEBUG [17-04-2025 13:21:53:991]: Handling C-MOVE Response
ERROR [17-04-2025 13:21:53:991]: DIMSE status is: Failed: UnableToProcess`
